import org.example.marathonservice.param.HealthAuditParam

rule "不适合参赛"
    when
        param : HealthAuditParam(
            haveChronicDisease == 1 ||
            haveDoctorAdvice == 1 ||
            haveFamilySuddenDeath == 1
        )
    then
        param.setRiskLevel(4);
        System.out.println("不适合参加比赛：存在慢性病、医生建议等高风险因素");
        drools.halt();
end

rule "可参加全马"
    when
        param : HealthAuditParam(
            haveChronicDisease == 2 &&
            haveDoctorAdvice == 2 &&
            haveFamilySuddenDeath == 2 &&
            (pastYearRace == 2 || pastYearRace == 1) // 有全马、半马经历
        )
    then
        param.setRiskLevel(1);
        System.out.println("可参加全马：身体健康，有全马经历");
        drools.halt();
end

rule "可参加半马"
    when
        param : HealthAuditParam(
            haveChronicDisease == 2 &&
            haveDoctorAdvice == 2 &&
            (pastYearRace == 2 || pastYearRace == 1)
        )
    then
        param.setRiskLevel(2);
        System.out.println("可参加半马：身体良好，有半马或全马经历");
        drools.halt();
end

rule "Eligible for 5k/10k"
    when
        param : HealthAuditParam(
            haveChronicDisease == 2 &&
            pastYearRace == 3
        )
    then
        param.setRiskLevel(3);
        System.out.println("可参加5K/10K：无重大疾病，缺乏比赛经验");
        drools.halt();
end

//rule "Need manual review"
//    when
//        param : HealthAuditParam(needReview == 1)
//    then
//        param.setRiskLevel(5);
//        System.out.println("需要人工复审");
//end

rule "Default pending review"
    when
        param : HealthAuditParam(riskLevel == null)
    then
        param.setRiskLevel(0);
        System.out.println("默认设置为未审核");
end
